// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.proto

/*
Package profile is a generated protocol buffer package.

It is generated from these files:
	profile.proto

It has these top-level messages:
	ProfileRequest
	ProfileResponse
*/
package profile

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProfileRequest struct {
	Name    string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Age     int64  `protobuf:"varint,2,opt,name=Age" json:"Age,omitempty"`
	City    string `protobuf:"bytes,3,opt,name=City" json:"City,omitempty"`
	Country string `protobuf:"bytes,4,opt,name=Country" json:"Country,omitempty"`
}

func (m *ProfileRequest) Reset()                    { *m = ProfileRequest{} }
func (m *ProfileRequest) String() string            { return proto.CompactTextString(m) }
func (*ProfileRequest) ProtoMessage()               {}
func (*ProfileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProfileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProfileRequest) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *ProfileRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *ProfileRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type ProfileResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *ProfileResponse) Reset()                    { *m = ProfileResponse{} }
func (m *ProfileResponse) String() string            { return proto.CompactTextString(m) }
func (*ProfileResponse) ProtoMessage()               {}
func (*ProfileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProfileResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ProfileRequest)(nil), "profile.ProfileRequest")
	proto.RegisterType((*ProfileResponse)(nil), "profile.ProfileResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Profile service

type ProfileClient interface {
	CreateProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
}

type profileClient struct {
	cc *grpc.ClientConn
}

func NewProfileClient(cc *grpc.ClientConn) ProfileClient {
	return &profileClient{cc}
}

func (c *profileClient) CreateProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := grpc.Invoke(ctx, "/profile.Profile/CreateProfile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Profile service

type ProfileServer interface {
	CreateProfile(context.Context, *ProfileRequest) (*ProfileResponse, error)
}

func RegisterProfileServer(s *grpc.Server, srv ProfileServer) {
	s.RegisterService(&_Profile_serviceDesc, srv)
}

func _Profile_CreateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).CreateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.Profile/CreateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).CreateProfile(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Profile_serviceDesc = grpc.ServiceDesc{
	ServiceName: "profile.Profile",
	HandlerType: (*ProfileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProfile",
			Handler:    _Profile_CreateProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile.proto",
}

func init() { proto.RegisterFile("profile.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x28, 0xca, 0x4f,
	0xcb, 0xcc, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x52, 0xb8,
	0xf8, 0x02, 0x20, 0xcc, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x16, 0xbf,
	0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x48, 0x80, 0x8b, 0xd9,
	0x31, 0x3d, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x39, 0x08, 0xc4, 0x04, 0xa9, 0x72, 0xce, 0x2c,
	0xa9, 0x94, 0x60, 0x86, 0xa8, 0x02, 0xb1, 0x85, 0x24, 0xb8, 0xd8, 0x9d, 0xf3, 0x4b, 0xf3, 0x4a,
	0x8a, 0x2a, 0x25, 0x58, 0xc0, 0xc2, 0x30, 0xae, 0x92, 0x36, 0x17, 0x3f, 0xdc, 0x96, 0xe2, 0x82,
	0xfc, 0xbc, 0xe2, 0x54, 0x90, 0xe2, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0x74, 0x98, 0x4d, 0x30, 0xae,
	0x91, 0x3f, 0x17, 0x3b, 0x54, 0xb1, 0x90, 0x0b, 0x17, 0xaf, 0x73, 0x51, 0x6a, 0x62, 0x49, 0x2a,
	0x4c, 0x40, 0x5c, 0x0f, 0xe6, 0x0f, 0x54, 0x57, 0x4b, 0x49, 0x60, 0x4a, 0x40, 0x2c, 0x52, 0x62,
	0x70, 0x12, 0x73, 0x12, 0x0a, 0x4e, 0xcc, 0x2d, 0xc8, 0x81, 0x99, 0x12, 0x00, 0x0a, 0x82, 0x00,
	0xc6, 0x24, 0x36, 0x70, 0x58, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xf8, 0xc3, 0x01,
	0x1c, 0x01, 0x00, 0x00,
}
